version: 0.2
phases:
  build:
    commands:
      - docker login -u $dockerhub_username -p $dockerhub_password
      - ls
      - docker run --rm -w /src markhobson/maven-chrome:latest mvn clean verify --file *.pom

artifacts:
  files:
    - ./**/*
